### ISSUE TITLE
[Ray Tune integration] wandb.ray.WandbLogger only tracks 1st trial w/o reinit=True in config

### ISSUE THREAD

**Issue by mikearango** [wandb/gitbook#22]
The Ray Tune [example docs](https://docs.wandb.com/library/integrations/ray-tune) (code snippet shown below) do not work as expected when integrating the `WandbLogger`.

```
from ray import tune
from wandb.ray import WandbLogger

tune.run("PG", loggers=[WandbLogger], config={
           "monitor": True, "env_config": {
               "wandb": {"project": "my-project-name", "monitor_gym": True}}})
```

If you add the `WandbLogger` to a hyperparameter tuning experiment with more than 1 trial by following the example docs, then only your first trial will be logged by the `WandbLogger`:
```
from ray import tune
from wandb.ray import WandbLogger

tune.run(experiment_function, num_samples=4, loggers=[WandbLogger], config={
    "lr": tune.sample_from(lambda spec: 10**(-10 * np.random.rand())),
    "momentum": tune.uniform(0.1, 0.9),
    "env_config": {
        "wandb": {
            "project": "my-project-name"
        }
    }
})
```

For Ray Tune experiments with more than 1 trial, you have to adjust your wandb config to include `reinit=True` since it defaults to `False` and will not reinitialize the logger at the start of each trial otherwise: 
```
tune.run(experiment_function, num_samples=4, loggers=[WandbLogger], config={
    "lr": tune.sample_from(lambda spec: 10**(-10 * np.random.rand())),
    "momentum": tune.uniform(0.1, 0.9),
    "env_config": {
        "wandb": {
            "project": "my-project-name", 
            # add "reinit": True to pass to wandb.init
            "reinit": True
        }
    }
})
```

**Comment by richardliaw** [comment]
This should be fixed in the latest version of the wandblogger:

https://docs.wandb.com/library/integrations/ray-tune

**Comment by mikearango** [comment]
@richardliaw Thanks for the update and reply. Keep up the awesome work on Ray. I'll close out the issue since this is fixed now.
