### ISSUE TITLE
Responsive panel configuration seems to be broken for image section 

### ISSUE THREAD

**Issue by jqueguiner** [wandb/gitbook#25]
Responsive panel configuration seems to be broken for image section 
https://streamable.com/ricvma
https://app.wandb.ai/jilijeanlouis/ovh-automl-image-classification-train-resnet50-%5B'homey-brown-dhole'%5D?workspace=user-jilijeanlouis

**Comment by cvphelps** [comment]
Hi @jqueguiner apologies for not seeing this issue! Could you please use our [main issue tracker](https://github.com/wandb/client) for issues with Weights & Biases?
